const prendas = [
  "Os noivos - fazer uma declaração de amor",
  "Dançar na boquinha da garrafa",
  "Imitar o choro da Chiquinha do Chaves",
  "Imitar uma galinha cacarejar",
  "Imitar um macaco se coçando",
  "Chupar limão sem fazer careta e sem sal",
  "Imitar o Michael Jackson",
  "Dar um beijo de lingua",
  "Imitar o som de uma Vaca",
  "Faça a seguinte declaração, bem emocionada para uma vassoura: Saiba que o meu grande amor hoje vai se casar, mandou uma carta para me avisar, deixou em pedaços o meu coração. E para matar a tristeza só mesa de bar, quero tomar todas vou me embriagar. Se eu pegar no sono me deite no chão.",
  "Em 15 segundos falar o nome de 10 personagens de desenho animado",
  "Cantar uma música em outra língua",
  "Em 10 segundos falar 5 nomes que se iniciem com a mesma letra do nome do noivo",
  "Conte uma situação engraçada que você e o NOIVO(A) passaram juntos",
  "Beber refrigerante no prato",
  "Cante e dance a música da XUXA",
  "Convide duas amigas para dançar a musica da Beyonce",
  "Dançar forro com o outro, com uma laranja na testa",
  "Declaração de amor com os objetos da caixa",
  "Pegar o anel com a língua no copo de água",
  "O que você faria se os alienígenas invadissem a terra?",
  "Conte um vexame que passaram juntos",
  "Conte uma briga que tiveram por algo totalmente sem noção/necessidade de discussão.",
  "Fazer moon walk",
  "Imite o Jackie chan em uma luta."
];
